version: '3.9'
services:
  angular-scaffold:
    container_name: kenjo-angular-webapp
    image: ridao/kenjo:latest
    ports:
      - "80:4200"
    command: ng serve --host 0.0.0.0 --port 4200
  app:
    container_name: kenjo-cd-collection
    image: gonzalokenjo/kenjo-challenge
    ports:
      - '3000:3000'
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - '27017:27017'
    